### PR TITLE
新增ARK ALL友鏈

### PR DESCRIPTION
**Pull request by yyyyyyounger**

### CODE REVIEW

**Comment by yyyyyyounger** [comment]
@BoxMars 快來confirm😘

**Comment by Admittedly-Goat** [comment]
Hello, thank you for your contribution. After carefully reviewing your commit, I personally believe that the center alignment of the navbar does not align with our design principles.

Regarding the sponsor link of UM ARK, I don't have any specific feedback to share at the moment.

**Comment by yyyyyyounger** [comment]
> 

The change of Nav style is same as the current website when display. 
I think The lack of alignment styles in older versions of code can lead to confusion when the height of child elements is too high. So I add it into class.
Of course, if don't modify the text on the navigation bar, nothing will happen. 

So, if you can share more about the design principles of the website. That is helpful. Thanks. 

image

**Comment by Admittedly-Goat** [comment]
LGTM. I have gotton the same result.

I think boxmars will determine whether the sponsor link is suitable for 选咩课 very soon, please be patient.
________________________________

**Comment by yyyyyyounger** [comment]
@BoxMars 又有更新啦😘

**Pull request closed without merging**
